FROM quay.io/centos/centos:stream8

# Install all dependencies available in RPM repos
RUN dnf -y update && \
    dnf -y install git-2.31.1 && \
    dnf -y clean all

COPY func.sh /usr/local/bin/func.sh
COPY create.sh /usr/local/bin/create_patches
RUN chmod +x /usr/local/bin/create_patches

RUN mkdir -p /work && chmod 777 /work
WORKDIR /work

ENV HOME /work

ENTRYPOINT ["create_patches"]
