FROM quay.io/centos/centos:stream9

RUN dnf -y update && \
    dnf -y install git-2.31.1 && \
    dnf -y clean all

COPY func.sh /usr/local/bin/func.sh
COPY create-patches.sh /usr/local/bin/create-patches
RUN chmod +x /usr/local/bin/create-patches

RUN mkdir -p /work && chmod 777 /work
WORKDIR /work

ENV HOME /work

ENTRYPOINT ["create-patches"]
