name: Lint
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
      name: Shellcheck
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
  container-lint:
    runs-on: ubuntu-20.04
    name: "Hadolint"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v12
        with:
          files: |
            ^Dockerfile.*$
          separator: " "
      - uses: jbergstroem/hadolint-gh-action@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          dockerfile: "${{ steps.changed-files.outputs.all_changed_files }}"