name: Tests
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:    
  bats-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Execute BATS tests
        run: |
          make test
        shell: bash